import { useState } from "react";
import "./EmailDetailsWindow.css";
import AccountDetailsWindow from "./AccountDetailsWindow";
import type { Account, EmailEntry } from "../types";
import { addAccount, removeAccount, saveData } from "../api";

export default function EmailDetailsWindow({ email, onBack, onUpdateEmail }: { email: EmailEntry; onBack: () => void; onUpdateEmail: (updated: EmailEntry) => void }) {
  const [showForm, setShowForm] = useState(false); const [newCompany, setNewCompany] = useState(""); const [newAccountName, setNewAccountName] = useState(""); const [newPassword, setNewPassword] = useState(""); const [searchQuery, setSearchQuery] = useState(""); const [selectedAccount, setSelectedAccount] = useState<Account | null>(null);
  const update = (accounts: Account[]) => onUpdateEmail({ ...email, accounts });
  const handleAddAccount = async (event: React.FormEvent) => { event.preventDefault(); if (newCompany && newPassword) { try { const id = await addAccount(email.email, newCompany, newPassword, newAccountName || "No Name"); await saveData(); update([...email.accounts, { id, company: newCompany, accountName: newAccountName || "No Name", password: newPassword }]); setNewCompany(""); setNewAccountName(""); setNewPassword(""); setShowForm(false); } catch (error) { window.alert(String(error)); } } };
  const filteredAccounts = email.accounts.filter((account) => account.company.toLowerCase().includes(searchQuery.toLowerCase()));
  if (selectedAccount) return <AccountDetailsWindow email={email} account={selectedAccount} onBack={() => setSelectedAccount(null)} onUpdateAccount={(updated) => { update(email.accounts.map((account) => account.id === updated.id ? updated : account)); setSelectedAccount(updated); }} />;
  return <div className="main-container"><div className="email-details-header"><button className="back-button" onClick={onBack}>← Back</button><h1>📧 {email.email}</h1><div style={{ width: "60px" }}></div></div><div className="email-details-content"><div className="accounts-top-section"><button className="add-button" onClick={() => setShowForm(!showForm)}>{showForm ? "Cancel" : "+ Add Account"}</button>{email.accounts.length > 0 && <input type="text" placeholder="Search accounts..." value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} className="search-bar" />}</div>{showForm && <div className="add-form-container"><form onSubmit={handleAddAccount} className="add-form"><input type="text" value={newCompany} onChange={(event) => setNewCompany(event.target.value)} placeholder="Company name (e.g., GitHub)" required autoFocus /><input type="text" value={newAccountName} onChange={(event) => setNewAccountName(event.target.value)} placeholder="Account name (optional, e.g., username)" /><input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="Password" required /><button type="submit" className="save-button">Save Account</button></form></div>}<div className="accounts-container">{email.accounts.length === 0 ? <p className="empty-message">No accounts saved for this email</p> : filteredAccounts.length === 0 ? <p className="empty-message">No accounts match your search</p> : <div className="accounts-list">{filteredAccounts.map((account) => <div key={account.id} className="account-card"><div className="account-card-clickable" onClick={() => setSelectedAccount(account)}><div className="account-info"><p className="account-name"><strong>Company:</strong> {account.company}</p><p className="account-password"><strong>Account:</strong> {account.accountName}</p></div></div><button className="delete-button" onClick={async (event) => { event.stopPropagation(); try { await removeAccount(email.email, account.id); update(email.accounts.filter((entry) => entry.id !== account.id)); } catch (error) { window.alert(String(error)); } }} title="Delete">🗑️</button></div>)}</div>}</div></div></div>;
}